README.rst
1. Remove leading '>' in command-line instructions. @cecilehannay felt (and I agree) that this does more harm than good, because you can't copy/paste.
2. Add a note about the 'detached HEAD' message
=> Documentation tweaks

CESM.cfg, ChangeLog
@jedwards4b wanted the externals updated to match cesm2_0_alpha08f.
Update externals in CESM.cfg.
Update ChangeLog to cesm2_0_alpha08f.
Testing:
unit tests:
system tests:
manual testing:ERS.f45_g37_rx1.A.cheyenne_intel, SMS.f09_g17.B1850.cheyenne_intel.allactive-defaultio
=> Updating to cesm2_0_alpha08f

cime_config/testlist_allactive.xml
Add allactive aux_cime_baseline tests.
Add SMS_Ld2.f09_g17.B1850.cheyenne_intel and SMS_N3_PM3Ld2.f19_g17.B1850Ws.cheyenne_gnu
tests to the aux_cime_baselines test category. 
Fixes:
Testing:
unit tests:
system tests:
manual testing: SMS_N3_PM3Ld2.f19_g17.B1850Ws.cheyenne_gnu.allactive-defaultio
=> Add allactive aux_cime_baseline tests

cime_config/config_compsets.xml
The new refcase is the same as the old except for the CLM initial
condition file, which has been updated for compatibility with
clm5.0.dev006.
=> Point to new refcase

cime_config/config_compsets.xml
This reverts commit 6b5318ca256dbaede4e1d3c1e2acec21002acf93, reversing
changes made to 505caa868d1083400021d99538c9102eb23bc7a3.
We're going to put this change in later
=> Revert "Merge pull request #37 from billsacks/new_refcase"

cime_config/config_compsets.xml
The new refcases are the same as the old except for the CLM initial
condition file, which has been updated for compatibility with
clm5.0.dev006.
I have shown that these give bit-for-bit results with the old refcases
by comparing (1) B1850 and BW1850 runs done with clm5.0.dev005 with the
old refcases with (2) B1850 and BW1850 runs done with clm5.0.dev006 with
the new refcases.
User interface changes?: No/Yes
Testing:
unit tests:
system tests:
- SMS_Ld1.f09_g17.B1850.cheyenne_intel.allactive-defaultio
- SMS_Ld1.f09_g17.BW1850.cheyenne_intel.allactive-defaultio
=> Point to new refcases for fully-coupled compsets

manage_externals/manic/checkout.py, manage_externals/manic/repository_svn.py
Minor updates to manage_externals
- Explain question mark in output (https://github.com/ESMCI/manage_externals/pull/102)
- Make no-logging the default (https://github.com/ESMCI/manage_externals/pull/103)
Fixes: None
Testing: None
unit tests:
system tests:
=> New version of manage_externals

doc/source/downloading_cesm.rst, doc/source/introduction.rst, doc/source/quickstart.rst
Documentation updates. 
User interface changes?: [ No/Yes ] None
Fixes: [Github issue #s] #50
=> remove prefix '>' from command line documentation

doc/source/downloading_cesm.rst
I have removed the reference to the log file, since that is no longer
produced by default. In its place, I have expanded the information on
checking manage_externals status.
=> Rework instructions for checking manage_externals status

doc/source/downloading_cesm.rst
removed doc references to SVN authentication as all release branches for CAM, POP, WW3 and 
the inputdata repo are now accessible via SVN anon http access.
=> doc update in response to user feedback

cime_config/config_compsets.xml
add %ABIO-DIC modifier to POP2 in B1850 and BHIST compsets
This modifier turns on two tracers in POP, for CMIP6 diagnostics.
requires pop2/trunk_tags/cesm_pop_2_1_20180912
Testing:
unit tests:
system tests:
ERS_Ld7.f09_g17.B1850.cheyenne_intel.allactive-defaultio
ERS_Ld7.f09_g17.BHIST.cheyenne_intel.allactive-defaultio
Tests passed
NLCOMP failed because turning on abio_dic_dic14 tracers in POP adds vars to pop_in
BASELINE pased
=> Enable POP CMIP6 diagnostic tracers in B1850, BHIST compsets

cime_config/testlist_allactive.xml, cime_config/testmods_dirs/allactive/cmip6/include_user_mods, cime_config/usermods_dirs/cmip6/include_user_mods
This can be used with a create_newcase command like this:
./create_newcase --case mycase --compset B1850 --res f09_g17 \
--user-mods-dir cmip6
This should probably also include user mods for CAM and maybe others.
Testing: Setup a test like the one added, but on my local machine;
ensured that user_nl_clm and user_nl_cice were as expected.
=> Add a top-level cmip6 usermods directory

cime_config/config_compsets.xml, cime_config/config_pes.xml, cime_config/testlist_allactive.xml
Add 4xCO2 and 1PCT compsets 
WACCM abrupt4xCO2: alias BWCO2x4
based on BW1850
RUN_REFCASE: b.e21.BW1850.f09_g17.CMIP6-piControl.001
RUN_REFDATE: 0070-01-01
RUN_STARTDATE: 0001-01-01
flbc_file = '/glade/p/cesmdata/cseg/inputdata/atm/waccm/lb/LBC_CMIP6abrupt4xCO2_cyclicalYear1_0p5degLat_c180929.nc'
flbc_cycle_yr = 1
CAM abrupt4xCO2: alias BCO2x4
based on B1850
co2vmr = 1138.8e-6
RUN_REFCASE: b.e21.B1850.f09_g17.CMIP6-piControl.001
RUN_REFDATE: 0601-01-01?
RUN_STARTDATE: 0001-01-01
WACCM 1pctCO2: alias BW1PCT
based on BW1850
RUN_REFCASE: b.e21.BW1850.f09_g17.CMIP6-piControl.001
RUN_REFDATE: 0070-01-01
RUN_STARTDATE: 0001-01-01
flbc_file = '/glade/p/cesmdata/cseg/inputdata/atm/waccm/lb/LBC_CMIP6_1pctCO2ramp_y1-165_0p5degLat_c180930.nc'
flbc_type = 'SERIAL'
CAM 1pctCO2: alias B1PCT
based on …
=> add 4xCO2 and 1PCT compsets

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
Change RUN_REFDATE for BCO2x4 and B1PCT from year 601 to 501.
User interface changes?: NO
Testing:
unit tests:
system tests:
=> Change ref year from 601 to 501 for BCO2x4 and B1PCT

cime_config/config_pes.xml, cime_config/testmods_dirs/allactive/cmip6/include_user_mods
Fix testing and pes for B1PCT and BCO2x4 compsets 
The cmip6 testmod for these compsets need to increase the frequency of the outputs in
order to pass restart tests.  ../defaultio include was added to the cmip6 testmod.
These compsets also failed to make any pes matches and were set to a bad default.  A match was
added for these compsets.
Testing:
unit tests:
system tests:
manual testing: ERS.f09_g17.BCO2x4.cheyenne_intel.allactive-cmip6
ERS.f09_g17.B1PCT.cheyenne_intel.allactive-cmip6
ERS.f09_g17.B1850.cheyenne_intel.allactive-defaultio
ERS.f09_g17.BW1850.cheyenne_intel.allactive-defaultio
=> Fix testing and pes layout for B1PCT and BCO2x4 compsets 

cime_config/config_pes.xml
The config_pes.xml for B compset matches not having a cam modifier was left out of PR #80.
Testing:
unit tests:
system tests:
manual testing: B1850, BW1850, B1PCT, BW1PCT, BCO2x4, and BWCO2x4 on cheyenne, 
compared env_mach_pes.xml.
=> Fix config_pes.xml for B compsets.

cime_config/testlist_allactive.xml
BW4xCO2 in the testlist is an invalid compset name.  It is renamed to BWCO2x4 to match
the existing compset name.  
Testing:
unit tests:
system tests:
=> Rename BW4xCO2 test to BWCO2x4 in order to match the correct compset

cime_config/testlist_allactive.xml
One the tests was using the cmip6 testmod that shoudn't have been.  And another test should have been using the cmip6 testmod. 
Testing:
unit tests:
system tests:
=> Fix cmip6 testmods

cime_config/testmods_dirs/allactive/cesm2dev01/include_user_mods, cime_config/testmods_dirs/allactive/cesm2dev01io/include_user_mods, cime_config/testmods_dirs/allactive/cism/oneway/README, cime_config/testmods_dirs/allactive/cism/oneway/shell_commands, cime_config/testmods_dirs/allactive/cism/trilinos/README, cime_config/testmods_dirs/allactive/cism/trilinos/include_user_mods, cime_config/testmods_dirs/allactive/cism/trilinos/shell_commands, cime_config/testmods_dirs/allactive/cism/trilinos/user_nl_cism
Just a bit of cleanup: As far as I can tell, these testmods directories are unused.
Fixes: None
Testing: None
=> Remove unused testmods directories

cime_config/usermods_dirs/README, cime_config/usermods_dirs/b1850/user_nl_cpl
Also, put a README file under cime_config/usermods_dirs (though,
admittedly, the main purpose of doing that was so that git would keep
the usermods_dirs directory around without anything else under it).
Fixes: #77 
Testing: none
=> Remove no-longer-needed b1850 usermods directory

cime_config/config_pes.xml
Adds a pelayout size L for the f19_g17 B case on cheyenne.   48 ypd
User interface changes?: 
Testing:
unit tests:
system tests: PFS_PL.f19_g17.B1850.cheyenne_intel.allactive_defaultio
=> add L pelayout for f19 on cheyenne

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
Stub wave compsets were added to be able to run multi-instance since. At the time, WW3 didn't
support multi-instance. WW3 supports multi-instance now, so the stub wave compsets are no
longer needed.
Testing:
unit tests:
system tests:
manual testing:  NCK.f19_g17.B1850.cheyenne_intel
=> Remove stub wave compsets for cesm2.2

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
Stub wave compsets were added to be able to run multi-instance since.   At the time, WW3 didn't
support multi-instance.  WW3 supports multi-instance now, so the stub wave compsets are no 
longer needed.
Testing:
unit tests:
system tests:
manual testing: NCK.f19_g17.B1850.cheyenne_intel
=> Remove stub wave compsets for cesm2.1

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
This isn't working as written. Part of the problem is that the datm data
it points to aren't available. It could be updated to point to
CRUv7. However, that still leaves an issue of where to get the CO2
forcing data if we want this compset to replicate what's actually being
used for LIWG spinup work (which uses _BGC%BDRD). Rather than trying to
resolve this now, @katetc and I thought it best to just remove this
compset for the CESM2.1 release and then revisit this for a later
release.
User interface changes?: Yes
No J1850G compset
Testing: none
=> Remove J1850G compset for now

cime_config/config_compsets.xml
Use cmip6 refcases for standard B and BW compsets.
This changes behavior for B1850, BHIST, BW1850, BWHIST and BWma1850
compsets.
Julio Bacmeister and Andrew Gettelman would like the standard B1850 and
BHIST compsets to basically match B1850cmip6 / BHISTcmip6. This requires
using the same refcase for the non-cmip6 compsets as for the cmip6
compsets. Rolando Garcia confirmed that he wants to do the same thing
for WACCM compsets as for CAM compsets in this respect.
This PR accomplishes this by generalizing the refcase matching regular
expressions, and by ensuring that CLM uses init_interp for the standard
B1850 / BHIST compsets (which is needed because the refcases have
virtual glaciers in Antarctica, whereas the standard B1850 / BHIST
compsets do not). BHISTcmip6 was already set up to use …
=> Use cmip6 refcases for standard B1850 and BHIST compsets

cime_config/testlist_allactive.xml
Add a restart test for BWCO2x4cmip6 and BWHISTcmip6.
Testing:
unit tests:
system tests:
=> Add a restart test for BWCO2x4cmip6 and BWHISTcmip6.

cime_config/testlist_allactive.xml, cime_config/testmods_dirs/allactive/defaultio_noclminterp/README, cime_config/testmods_dirs/allactive/defaultio_noclminterp/include_user_mods, cime_config/testmods_dirs/allactive/defaultio_noclminterp/shell_commands, cime_config/testmods_dirs/allactive/defaultio_noclminterp/user_nl_clm
This avoids this error in the branch run of ERI tests:
```
ERROR: Can only set use_init_interp if finidat is set
```
Currently, ERI tests do a startup run for the ref1 case, so we don't
actually need the use_init_interp setting that we would normally need
for this compset-grid combination. So it's safe to simply turn off
use_init_interp for all of the cases in this ERI test.
Fixes: none
Testing:
unit tests:
system tests: ERI.f09_g17.B1850.cheyenne_intel.allactive-defaultio_noclminterp
=> Set CLM's use_init_interp=.false. for ERI f09_g17 B1850 tests

cime_config/config_compsets.xml
Fix the BW1850 compset by adding %NDEP to POP in the long name.
User interface changes?: NO
Testing:
unit tests:
system tests: SMS_Ld1.f09_g17.BW1850.cheyenne_intel.allactive-default
=> BW1850 compset fix

Externals.cfg, cime_config/config_compsets.xml
modified:   Externals.cfg
Correct WACCM SSP compset long names.
Remove the "-" and "." characters from compset long names.
Testing: bwaccm
=> Correct long names of the WACCM SSP compsets

ChangeLog, Externals.cfg, cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
Add SSP5-8.5 compsets and test
Add BSSP585, BSSP585cmip6 and a couple tests for it. Remove some of the RCP compsets and tests. This branch was made relative to cesm2.1.1-rc.01.
User interface changes?: Yes
New compsets for CMIP% SSP5-8.5 scenario
Fixes: #104 #97
#104 -- remove CMIP5 RCP's
#97 -- future scenario names need to change
Testing:
system testing: SMS_D_Ld1.f09_g17_gl4.BSSP585cmip6.cheyenne_intel.allactive-defaultio PASS
=> Add SSP5-8.5 compsets and test

Externals.cfg, cime_config/config_compsets.xml
Update REFCASEs to work with new fsurdat files in release-clm5.0.20
REFCASES needed to be interpolated to work with new fsurdat files in release-clm5.0.20. This is the start of that process.
Fixes: #107
Testing:
system tests:
SMS_Ln1.f09_g17.B1850.cheyenne_intel.allactive-defaultio.20190314_115153_xlpcd1
SMS_Ln1.f09_g17.B1PCTcmip6.cheyenne_intel.allactive-defaultio_min.20190314_115153_xlpcd1
=> Create Interpolated REFCASEs for compsets

cime_config/config_compsets.xml
add B1850_BPRP, B1850_BPRPcmip6 compsets
compset definition, and REFCASE, added to
cime_config/config_compsets.xml
Testing:
passed following tests
ERS.f09_g17.B1850_BPRP.cheyenne_intel.allactive-defaultio
ERS.f09_g17.B1850_BPRPcmip6.cheyenne_intel.allactive-defaultio
visual inspection of env_run.xml and namelists to confirm BPRP settings
=> add B1850_BPRP, B1850_BPRPcmip6 compsets, including REFCASE

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
modified:   cime_config/testlist_allactive.xml
add compset BWmaHIST
add reference cases for 2-degrees WACCM
Testing:
bwaccm suite
SMS_D_Ld1.f09_g17.B1850cmip6.cheyenne_intel.allactive-defaultio_min (Overall: PASS) details:
SMS_Ld2.f09_g17.B1850.cheyenne_intel.allactive-defaultio (Overall: PASS) details:
SMS_Ld2.f09_g17.BHIST.cheyenne_intel.allactive-defaultio (Overall: PASS) details:
SMS_Ld2.f19_g17.B1850.cheyenne_intel.allactive-defaultio (Overall: DIFF) details:
SMS_Ld2.f19_g17.BHIST.cheyenne_intel.allactive-defaultio (Overall: DIFF) details:
=> add 2-degree support, BWmaHIST

manage_externals/manic/checkout.py, manage_externals/manic/repository_factory.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py
Add ability to pass --ignore-ancestry to svn switch
Add --svn-ignore-ancestry option to argparse, and then pass it
through many calls to SvnRepository constructor. If this variable
is True, run svn switch --ignore-ancestry.
User interface changes?: Yes - added optional --svn-ignore-ancestry command line argument
Note that omitting the option retains past behavior.
Fixes: #113  Update manage_externals
Testing:
unit tests:
manual testing: Ran checkout_externals
=> Update manage_externals to v1.1.6 for master.

manage_externals/manic/checkout.py, manage_externals/manic/repository_factory.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py
Add ability to pass --ignore-ancestry to svn switch
Add --svn-ignore-ancestry option to argparse, and then pass it
through many calls to SvnRepository constructor. If this variable
is True, run svn switch --ignore-ancestry.
User interface changes?: Yes - added optional --svn-ignore-ancestry command line argument
Note that omitting the option retains past behavior.
Fixes: #113  Update manage_externals
Testing:
unit tests:
system tests: 
manual testing: Ran checkout_externals
=> Update manage_externals to v1.1.6 for cesm2.0 alpha branch.

Externals.cfg, cime_config/config_compsets.xml
Add non-WACCM SSP2-RCP4.5 and SSP3-RCP7.0 compsets
Add two new CMIP6 future scenario compsets (total of four as there are ones with cmip6 use-case turned on and ones without)
User interface changes?: N (other than addition of new compsets)
Fixes: [Github issue #s] And brief description of each issue. None
Testing:
system tests:
SMS_Ln1.f09_g17.BSSP245.cheyenne_intel.allactive-defaultio
SMS_Ln1.f09_g17.BSSP370.cheyenne_intel.allactive-SMS_Ln1.f09_g17.BSSP245cmip6.cheyenne_intel.allactive-defaultio
SMS_Ln1.f09_g17.BSSP370cmip6..cheyenne_intel.allactive-defaultio
=> Add BSSP245 and BSSP370 compsets

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
modified:   cime_config/testlist_allactive.xml
- changes needed for 2-degree cmip6 runs
- added new waccm middle atmosphere chemistry compsets
Testing:
system tests: bwaccm
=> Add WACCM mid-atmos chem compsets; adjust waccm 2-deg ref cases

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
moved some BPRP pattern matches up in cime_config/config_compsets.xml
to avoid matching to non-BPRP patterns
Testing:
passed following tests
ERS_Ld5.f09_g17.B1850_BPRP.cheyenne_intel.allactive-defaultio
ERS_Ld5.f09_g17.BHIST_BPRP.cheyenne_intel.allactive-defaultio
confirmed that RUN_REFCASE is correct in tests
=> correct RUN_REFCASE and add tests for BPRP compsets

cime_config/testlist_allactive.xml
Fix ERS_Ld5 B compset tests that were too short.
ERS_Ld5.f09_g17.B1850_BPRP.cheyenne_intel.allactive-default and ERS_Ld5.f09_g17.BHIST_BPRP.cheyenne_intel.allactive-default were failing the restart test in pop pop.h.once file because the test was configured to be too short.  This was fixed by using the defaultio_min testmod that increased the io frequency of pop.
User interface changes?: [No
Testing:
unit tests:
system tests:
manual testing:ERS_Ld5.f09_g17.B1850_BPRP.cheyenne_intel.allactive-defaultio_min
ERS_Ld5.f09_g17.BHIST_BPRP.cheyenne_intel.allactive-defaultio_min
=> Fix ERS_Ld5 B compset tests with defaultio_min testmod

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
Rename BWma1850cmip6 and BWmaHISTcmip6 to BWma1850 and BWmaHIST.
Remove f0.9 BWma1850/BWmaHIST tests.  Remove BC5L45BGCR test.
Fixes: [Github issue #s] 
Testing:
unit tests:
system tests:
=> Rename BWma1850cmip6 and BWmaHISTcmip6

cime_config/testlist_allactive.xml
Remove BWSSP534os and BWSSP534oscmip6 tests that aren't support and
are failing the tests.
=> Remove failing BWSSP534os tests

.gitignore, Externals.cfg
Adds MOM6 as an optional component and FMS as an optional library in CESM.
User interface changes?: No/Yes
Fixes: n/a
Testing:
aux_mom
=> Add MOM6 and FMS as Optional Externals

doc/README, doc/source/downloading_cesm.rst
gh-pages sphinx redirect updates for 
https://github.com/ESCOMP/cesm -> https://github.com/ESCOMP/CESM
update for latest release-cesm2.1.1 download instructions
=> updates for redirect

describe_version
This describes the CESM version and any local modifications.
This is mainly to help users describe their CESM version for the sake of
forum posts.
Fixes: ESCOMP/cesm#132 (Add a script that prints version information)
Testing:
unit tests: none
system tests: none
manual testing: Ran script with and without local modifications, invoked from current directory and from elsewhere. Also ran pylint on the new code.
Here is sample output. I am happy to tweak the output format if others prefer something different. I have deliberately made the output pretty verbose to help avoid initial back-and-forths with people posting to the forums: I wanted to be able to see any files they have changed in their sandbox. However, note that it's also possible to just get a quick view …
=> Add describe_version script

describe_version
This describes the CESM version and any local modifications.
This is mainly to help users describe their CESM version for the sake of
forum posts.
Fixes: ESCOMP/cesm#132 (Add a script that prints version information)
Testing:
unit tests: none
system tests: none
manual testing: Ran script with and without local modifications, invoked from current directory and from elsewhere. Also ran pylint on the new code.
Here is sample output. I am happy to tweak the output format if others prefer something different. I have deliberately made the output pretty verbose to help avoid initial back-and-forths with people posting to the forums: I wanted to be able to see any files they have changed in their sandbox. However, note that it's also possible to just get a quick view …
=> Add describe_version script (to master)

Copyright
Update to match http://www.cesm.ucar.edu/models/cesm2/copyright.html,
which is the copyright notice approved by UCAR legal.
In particular, note the removal of the term "public domain software",
because that is incorrect legal terminology.
Testing: none
unit tests:
system tests:
=> Update CESM2 copyright notice

Externals.cfg, cime_config/config_compsets.xml
Two SSP extensions from 2100 to 2300
Extensions from 2100-2300 for SSP5-8.5 and SSP5-3.4. Also started adding support for SSP1-2.6.
Fixes: #140 
Testing:
system tests: SMS_D.f09_g17.BWSSP534osextcmip6.cheyenne_intel.allactive-default and
SMS_D.f09_g17.BWSSP585extcmip6.cheyenne_intel.allactive-default
built, and ran (didn't run to completion)
=> Extensions to 2300 for SSP5-8.5 and SSP5-3.4

Externals.cfg, cime_config/config_compsets.xml
Fix issues with the 2300 extension compsets
Point to the POP branch tag needed for the extensions.
Set RUN_TYPE and GET_REFCASE for extensions
Remove the BWSSP126extcmip6 compset, as it can't be setup without creation of 2100-01-01 restart files.
Fixes: #149 -- Remove SSP126EXT compset
Fixes: #148 -- Set RUN_TYPE and GET_REFCASE for extension compsets.
Testing:
system tests: 
SMS_Ld1.f09_g17.BWSSP534osextcmip6.cheyenne_intel.allactive-default
SMS_Ld1.f09_g17.BWSSP585extcmip6.cheyenne_intel.allactive-default
=> Fix issues with the 2300 SSP extension compsets

CODE_OF_CONDUCT.md
Add the standard UCAR Code of Conduct (COC) to the cesm2.1 release branch
This adds the standard UCAR COC to the cesm2.1 release branch.
Fixes: 146
Testing: None (Documentation change only)
=> Add UCAR standard code of conduct to cesm2.1 release branch

CODE_OF_CONDUCT.md
Add the code of conduct to CESM project
This adds the standard UCAR code of conduct for behavior that is expected in the CESM project to master.
Fixes #146 
Testing: None (no code or script changes)
=> Add UCAR standard code of conduct

cime_config/config_compsets.xml
Needed to add %NDEP to POP to get BWma1850 compsets working.
User interface changes?: NO
Testing:
unit tests:
system tests:
manual testing: SMS_Ld5.f09_g17.BWma1850.cheyenne_intel.allactive-defaultio,
SMS_Ld5.f19_g17.BWma1850.cheyenne_intel.allactive-defaultio
=> Fix BWma1850 compset

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/01_bug_report.md, .github/ISSUE_TEMPLATE/02_enhancement.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
Updates the issue and PR templates. A major change is adding a bunch of links to other places where people should consider going for help or opening issues.
To see how this looks, go here: <https://github.com/billsacks/cesm/issues/new/choose>. My original plan was to just add a link to the CESM forums, but then I thought it could be useful to add links to open issues for any of the CESM externals. I'm not sure, though: Is this helpful or too much?
=> Update issue & PR templates

Externals.cfg, Externals_cime.cfg
Add mizuRoute as an external. This will also need an update to CTSM. This is just for the nuopc_dev branch right now.
There are also branch changes in CTSM that are needed for it to work.
Contributors other than yourself, if any: Naoki Mizukami
Testing performed (automated tests and/or manual tests): 
SMS_D_P5x1_Vnuopc_Ld5.5x5_amazon_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
SMS_D_P36x1_Vnuopc_Ld10.f19_g17_r05.I2000Clm50SpMizGs.cheyenne_intel.mizuroute-default
=> Add mizuRoute as an external

Externals_cime.cfg
Updates the CMEPS and CDEPS hashes and makes these components optional since they are not needed with the mct driver. 
=> update cmeps and cdeps and make them optional

Externals.cfg, cime_config/config_compsets.xml, cime_config/config_pes.xml
Description of changes
Add B1850MOM compset, add a pelayout for cheyenne, make MOM, RTM and FMS optional components
Specific notes
MOM, RTM and FMS are not needed by default in the cesm2.2 release.
Fixes: 
User interface changes?: [ Yes ]
Users who want to use these components will have to check them out explicitly with manage_externals
Testing performed (automated tests and/or manual tests):  
PFS.f09_t061.B1850MOM.cheyenne_intel
=> Add B1850MOM compset, add a pelayout for cheyenne, make MOM, RTM and FMS optional components

cime_config/config_compsets.xml
Have J1850G compset use CRUv7 data rather than the older version 4 data. We removed the version 4 off local disk to save space on cheyenne and CGD.
Fixes: #168 
SMS_Ld5.f09_g17_gl4.J1850G.cheyenne_gnu.allactive-cism-test_coupling PASSes
=> Fix for JG compset fixing #168

Externals.cfg
Update Externals.cfg to use uppercase repository names
Fixes: #128 
Manual manage_externals/checkout_externals -o
=> Update Externals.cfg to use uppercase repository names

doc/source/cesm_configurations.rst, doc/source/downloading_cesm.rst, doc/source/quickstart.rst
Update documentation for CESM2.2.0.
Juggled around CESM vs CESM2.  The approach I took was if it applied to both
CESM and CESM2, I left it as CESM.  For example the section on inputdata, and version 
naming.  If something applied to only CESM2, I changed CESM to CESM2.  An example 
of this is the download instructions and different components.
In the download instructions, I needed to update the manage_externals -S output to reflect
the changes of the option components.  Then  included a note that this is the default and 
CESM2 will still run.
=> Update docs for CESM2.2.0

doc/source/cesm_configurations.rst, doc/source/downloading_cesm.rst, doc/source/quickstart.rst
Bring in documenation updates from CESM2.2 that also apply to CESM2.1
=> Bring in documenation updates from CESM2.2 that also apply to CESM2.1

Externals.cfg, cime_config/config_compsets.xml
Adding HISTsmbb compset for CESM2-LE ensemble with smoothed BB burning and fixed SO2/SO4 forcing.
JF Lamarque (smoothing); Simone Tilmes (Corrected SO2/SO4 ship forcing)
=> adding HISTsmbb compset for smoothed BB

Externals.cfg, Externals_cime.cfg
Remove the Externals_cime.cfg file, no longer required.  
cmeps has was updated and  moved into Externals.cfg and cdeps hash was updated
The only test conducted here was a fresh checkout of the code.
=> Externals_cime is no longer needed, update cmeps and cdeps hashes

cime_config/config_compsets.xml, cime_config/config_pes.xml, cime_config/testlist_allactive.xml
As of cism2_1_74, CISM1 is no longer supported
Fixes: none
Testing performed (automated tests and/or manual tests): none
=> Remove CISM1 compset and test

cime_config/config_pes.xml
Rename Greenland grid gland4 to gris4
**This change needs to come in at the same time as cismwrap_2_1_80 and https://github.com/ESMCI/cime/pull/3943 - so tentatively, cesm2_3_alpha04b.**
Fixes: none
Testing performed (automated tests and/or manual tests): None
=> Rename Greenland grid gland4 to gris4 (cesm2_3_alpha04b)

Externals.cfg
This PR adds a new version of WW3 (v.6.07) to CESM as an optional wave component, called ww3dev. Initially both ww3 and ww3dev (optional) will coexist, but once ww3dev development is finalized, it will replace the old ww3. 
Contributors other than yourself, if any: @mvertens 
Fixes: [Github issue #s] n/a
Testing performed (automated tests and/or manual tests): C and CMOM SMS tests with the new ww3dev component.
=> Add a new version of WW3 as an optional component

cime_config/config_compsets.xml
Explicitly put GRIS (for Greenland Ice Sheet) in the long name. This
shouldn't change any behavior. CISM has been backwards compatible in
this respect, but making this compset long name change will allow us to
remove the backwards compatibility code in CISM.
Fixes ESCOMP/CESM#181
- Ran create_newcase with each of the changed compsets (but didn't run any further than that)
=> Change long names for CISM compsets

Externals.cfg
Update ww3dev entry in Externals.cfg to point to the new WW3_interface repository.  Also add an externals entry in ww3dev to point to the core WW3 repository.
MOM6+WW3DEV ERS tests
=> Update ww3dev entry in Externals.cfg for the new WW3 repo

cime_config/testlist_allactive.xml
Remove mct tests from the tests lists that are failing.  There are no plans to fix these tests since 
mct is being deprecated.
=> Remove mct tests.

cime_config/config_pes.xml
Add pelayouts for ne30pg3_t232.BLT1850_v0c on derecho
Fixes:
PFS.ne30pg3_t232.BLT1850_v0c.derecho_intel
All four new pelayouts were added to the timing table at https://csegweb.cgd.ucar.edu/timing/cgi-bin/timings.cgi?a=s
=> add derecho pelayouts remove retired systems

cime_config/config_pes.xml, cime_config/testmods_dirs/allactive/defaultiomi/shell_commands
There were some tests on derecho that failed due to the PES layouts.
Reduce the number of default nodes for WAV at 1 deg configuration.
Set the allactive-defaultiomi testmod NTASKS for ocn to 2 nodes.
PFS_Ld1.f09_g17.B1850.derecho_intel.allactive-defaultio
MCC.f19_g17.B1850.derecho_intel.allactive-defaultiomi.defaultpes
MCC.f19_g17.B1850.cheyenne_intel.allactive-defaultiomi
=> NTASK fixes for derecho prealpha tests.

cime_config/config_pes.xml
NTASKS_LND=NTASKS_ROF=ROOTPE_ICE=724 for ne30pg3_t232 BLT1850_v0c on cheyenne.  The correct value
should be 720 in order to use the all 36 tasks on a node.
Fixes:  Partially address #228.  There's no significant speed up.  
=> PES fix for ne30pg3_t232 BLT1850_v0c on cheyenne

cime_config/config_compsets.xml, cime_config/config_pes.xml
Add `BMT1850_MARBL` compset, use existing MT pe-layout for non-MARBL configurations, and introduce new MT+MARBL pe-layout
I told @jedwards4b already, but there's an issue with the existing MT layout: the ocean has 408 cores, starting at 5400, so the run uses 5808 cores -- that's 45 full nodes plus 48 cores on a 46th node. NTASKS_OCN should either get bumped up to 488 or dropped to 360.
Fixes: [Github issue #s] N/A
Ran PFS tests to ensure `BMT1850` and `BMT1850_MARBL` both get expected layouts.
=> Cesm3.0 more marbl

.gitmodules
Add CUPiD to the `tools/` directory
Having CUPiD in the CESM tree will make it easier to incorporate in the [CESM Workflow](https://github.com/ESMCI/ccs_config_cesm/pull/176)
Contributors other than yourself, if any: @teaganking and @ingridc2051 have done a lot of the heavy lifting towards incorporating CUPiD into CESM
Fixes: N/A
Testing performed (automated tests and/or manual tests): None (will start testing with the ccs_config_cesm branch soon)
=> Add CUPiD v0.1.0 to CESMROOT/tools

cime_config/config_compsets.xml
Set LND_SETS_DUST_EMIS_DRV_FLDS.
To avoid a conflict between CAM and CTSM dust emissions for B compsets, LND_SETS_DUST_EMIS_DRV_FLDS needs to be set.
SMS_Ld2.ne30pg3_t232.BLT1850.derecho_intel.allactive-defaultio
=> Set LND_SETS_DUST_EMIS_DRV_FLDS to avoid conflict between cam and clm.

.github/workflows/fleximod_test.yaml, .gitmodules
Adding the cesm3.0-alphabranch to 
github workflow tests.  
=> add alphabranch to tests 

.gitmodules, ChangeLog, cime_config/testlist_allactive.xml
Update externals and ChangeLog for cesm3_0_alpha04a.
Increase wallclock for prealpha ERI tests on derecho.
=> Updates for cesm3_0_alpha04a tag.

.gitmodules, ChangeLog
Issues were found with the cice tag during testing.   So the cice tag is being moved to cesm3_0_alpha04b
=> Revert cice tag.

.gitmodules, ChangeLog
Update externals to fix some failed prealpha tests.
=> Update for cesm3_0_alpha04b to fix some testing.

.gitmodules, ChangeLog
Update externals and ChangeLog for cesm3_0_alpha05a.
I don't think there should be any issues with updating the cime and cmeps tags.  But if testing shows issues, I'll back them out.
=> Update for cesm3_0_alpha05a

.gitmodules, ChangeLog
Reverted cime, cdeps, and ccs_config tags to address failed tests in alpha05a.
=> Revert cime/cdeps/ccs_config for alpha05a

.github/workflows/build.yaml, .github/workflows/derecho.yaml, .github/workflows/fleximod_test.yaml, .gitmodules, .lib/git-fleximod/git_fleximod/cli.py, .lib/git-fleximod/git_fleximod/git_fleximod.py, .lib/git-fleximod/git_fleximod/submodule.py, .lib/git-fleximod/poetry.lock, .lib/git-fleximod/pyproject.toml, .lib/git-fleximod/tbump.toml, .lib/git-fleximod/tests/conftest.py, cime_config/config_compsets.xml, cime_config/config_pes.xml, cime_config/testfiles/ExpectedTestFails.xml, cime_config/testlist_allactive.xml
Adds a workflow on derecho that builds fully active compsets with each of the four compiler sets. 
This PR should not be merged until the ccs_config and cam PRs are merged and the .gitmodules are updated.
Also updates git-fleximod to the latest tag.  
=> new workflow and compset aliases

.gitmodules
Update git modules for cesm3_0_alpha05b testing.
=> Update for cesm3_0_alpha05b testing

.gitmodules, cime_config/config_compsets.xml
Remove MARBL from fully coupled compsets, and add back MARBL specific compsets.
Backup cice tag to version that works with CAM due to issue https://github.com/ESCOMP/CICE/issues/36
=> Revert cice tag and update compsets.

.github/workflows/fleximod_test.yaml, .gitmodules
If the tags used by git fleximod in the `.gitmodules` do not match the externals checked in to the various components, then `git diff --exit-code` will fail. In this case, whichever components are triggering the failure should be updated to ensure `.gitmodules` and the actual externals match.
I verified that `git diff --exit-code` will return 1 if there are differences in any of the submodules (including differences in submodules of submodules) and 0 if everything is clean; I'm 99% sure this branch will fail the fleximod-test for non-zero return codes.
=> Add git diff to fleximod_test

.gitmodules, ChangeLog
Update cice tag.  This fixes a dependency with cam.
=> Update cice tag for cesm3_0_alpha06b

.lib/git-fleximod/git_fleximod/cli.py, .lib/git-fleximod/git_fleximod/git_fleximod.py, .lib/git-fleximod/git_fleximod/gitinterface.py, .lib/git-fleximod/git_fleximod/submodule.py, .lib/git-fleximod/pyproject.toml, .lib/git-fleximod/tbump.toml, .lib/git-fleximod/tests/conftest.py
Updates git-fleximod to v1.0.1
Courtney
Fixes: Issue https://github.com/ESMCI/git-fleximod/issues/75
=> Update fleximod 061825

.github/workflows/preview_namelist.yaml, cime_config/config_compsets.xml
[Spreadsheet](https://docs.google.com/spreadsheets/d/1nJl4lbbwBq60quyaERJ6OvVJxF4kDu4xX7zZenZgyB8/edit?usp=sharing)
=> update compsets to match cesm3 spreadsheet compsets 
