README.md, README.rst
@bertinia added a README.md file, but that masked the README.rst.  I
have modified README.rst to be consistent with the changes she made in
README.md.
=> Remove README.md, modify README.rst to have some changes from there

README.rst
Suggestion from Nan Rosenbloom to clarify part of README.
Testing: none, doc only.
=> Update README for clarity

doc/source/quickstart.rst
quickstart user's guide update of qcmd per @cacraigucar email request - no issue.
Fixes: [Github issue #s] None
Update gh-pages orphan branch? Yes
=> update qcmd option

doc/source/downloading_cesm.rst
@bertinia - if you agree with this change then the rst-based pages need to be regenerated.
=> Fix download url

Copyright
@whlipscomb if you'd like, you can review this to make sure I got it right.
=> Update CISM copyright

cime_config/config_pes.xml
pelayout for fully coupled on stampede2-skx
Fixes:
Testing:
unit tests:
system tests:
=> fully coupled balanced pelayout

doc/source/quickstart.rst
=> update format and fix typo

Externals.cfg
svn externals need to point to release_tags directories for anonymous access
Testing:
unit tests:
system tests:
=> fix svn anonymous access

doc/source/downloading_cesm.rst, doc/source/introduction.rst, doc/source/quickstart.rst
Suggest running for a month.
This way, the user will be able to see history files. This was suggested
by Gunter Leguy.
Also some other minor edits to the quickstart.
=> Update quick start documentation

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
Add BWHIST compset
Change reference case for BW* 1-degree cases
BWHIST needs CLM namelist setting use_init_interp=.true.
Add prebeta test for BWHIST
User interface changes?: [No
Fixes: [Github issue #s] 
Testing:
unit tests:
system tests:
manual testing:  SMS_Ld1.f09_g17.BWHIST.cheyenne_intel.allactive-defaultio
=> Add BWHIST compset and test

doc/source/downloading_cesm.rst
Quickstart doc source update for release-cesm2.0.1
Fixes: [Github issue #s] And brief description of each issue. None
Testing: N/A
unit tests:
system tests:
=> doc update for release-cesm2.0.1

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
Add WACCM-SC compsets BWsc1850, BWscHIST
Testing:
manual testing: bwaccm
=> Add WACCM-SC compsets 

cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
modified:   cime_config/testlist_allactive.xml
Add the SSP compsets for WACCM 
User interface changes?: no
Testing:
system tests: bwaccm
=> Add WACCM future scenario compsets

README.rst, doc/source/downloading_cesm.rst
Two small documentation tweaks
The tweak to the sphinx documentation is related to https://github.com/ESMCI/manage_externals/issues/115
=> Small documentation tweaks

Externals.cfg, cime_config/config_compsets.xml, cime_config/testlist_allactive.xml
modified:   Externals.cfg
modified:   cime_config/testlist_allactive.xml
Add compsets:
BWSSP245cmip6
BWSSP370cmip6
Testing: bwaccm
=> Updates to WACCM future scenario compsets:

cime_config/config_pes.xml
Add a pelayout for bluewaters f09_g17 B
Fixes: 
Testing:
unit tests:
system tests: PFS.f09_g17.BHIST.bluewaters_intel
=> update pelayout for bluewaters

ChangeLog, Externals.cfg, Externals_cime.cfg, manage_externals/manic/externals_description.py, manage_externals/manic/repository.py, manage_externals/manic/repository_git.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py, manage_externals/test/test_sys_checkout.py, manage_externals/test/test_unit_externals_description.py
add cmeps as an external and use latest version of manage_externals
Fixes: None
Testing: NA 
unit tests:
system tests:
=> add cmeps as an external and use latest version of manage_externals

cime_config/config_compsets.xml
Changes needed to finish 2deg DECK
Testing:
SMS_D_Ln9.f19_g17.BCO2x4cmip6.cheyenne_intel (Overall: PASS) details:
SMS_D_Ln9.f19_g17.BWma1PCTcmip6.cheyenne_intel (Overall: PASS) details:
SMS_Ld1.f19_g17.B1PCTcmip6.cheyenne_intel (Overall: PASS) details:
SMS_Ld1.f19_g17.BWma1PCTcmip6.cheyenne_intel (Overall: PASS) details:
SMS_Ld1.f19_g17.BWmaCO2x4cmip6.cheyenne_intel (Overall: PASS) details:
=> Updates from Mike Mills for 2-degrees resolution

cime_config/config_compsets.xml
Based on list from Mike Mills
Fixes: none
Testing:
unit tests: none
system tests: none
manual testing: none
=> Add science support to compsets

Externals_cime.cfg
Adds the fox xml library which is needed by the nuopc data models (CDMEPS)
=> Add fox fortran xml interface library

README.rst
Removed statement from README that some components might not work with python3.
Resolves #131
=> Removed statement about some components might not work with python3

doc/source/cesm_configurations.rst, doc/source/downloading_cesm.rst, doc/source/introduction.rst, doc/source/quickstart.rst
Fix broken links in documentation. 
Fixes: #160 
Testing performed (automated tests and/or manual tests): Clicked on all of the links.
=> Fix broken links in documentation. 

Externals.cfg, Externals_cime.cfg
Change cdeps version and location, so that nuopc tests can work.
Fixes #152 needs. updated CDEPS
Testing performed (automated tests and/or manual tests): run two nuopc tests
LILACSMOKE_Vnuopc_D_Ld2.f10_f10_musgs.I2000Ctsm50NwpSpAsRsGs.cheyenne_intel.clm-lilac
SMS_D_Ld5_Vnuopc.f10_f10_musgs.I2000Clm50BgcCropGs.cheyenne_intel.clm-default
=> Update CDEPS to work with cime fixes #152

manage_externals/.gitignore, manage_externals/.travis.yml, manage_externals/manic/checkout.py, manage_externals/manic/externals_description.py, manage_externals/manic/sourcetree.py, manage_externals/test/test_sys_checkout.py, manage_externals/test/test_unit_externals_description.py
Fixes: 
checked out code with latest manage_externals
=> bring in latest manage_externals

doc/source/cesm_configurations.rst, doc/source/downloading_cesm.rst, doc/source/quickstart.rst
Bring in documentation updates from cesm2.2-rcbranch.
=> Bring in documentation updates from cesm2.2-rcbranch.

Externals.cfg
nag port, used to generate cmeps baseline Mar12
Contributors other than yourself, if any: mvertens 
aux_cam on nag compiler, cmeps driver on cheyenne
=> Nuopc dev nag port

.github/ISSUE_TEMPLATE/config.yml
Add CDEPS to the issue chooser
Fixes: none
Testing performed (automated tests and/or manual tests): None
=> Add CDEPS to the issue chooser

Externals.cfg
Add CESM CIME Case Control System configuration files to externals.
Manual test of aux_cime_baselines testlist.
=> Add CESM CIME Case Control System to externals.

cime_config/testlist_allactive.xml
Remove test systems bluewaters, hobart and edison from testlists
=> remove obsolete tests

cime_config/config_compsets.xml
Adding SSP370smbbext compset to continue LE2 from 2100-2500
Adding compset:  SSP370smbbext
jim edwards
n/a
successfully tested compset on cheyenne
=> 2100extension compset

cime_config/config_compsets.xml
Set b.e21.BSSP370smbb.f09_g17.LE2-1171.009 as the REFCASE for BSSP370smbbext
@nanr 
=> Set b.e21.BSSP370smbb.f09_g17.LE2-1171.009 as the REFCASE for BSSP370smbbext

Externals.cfg
=> Move cice6 to cice.

.github/ISSUE_TEMPLATE/config.yml
Just changes the CESM issue chooser; no impact on anything else
Fixes: none
Testing performed (automated tests and/or manual tests): None
=> Add pointers to recently-added repositories in issue chooser

Externals.cfg, tools/statistical_ensemble_test/README, tools/statistical_ensemble_test/addmetadata.sh, tools/statistical_ensemble_test/ensemble.py, tools/statistical_ensemble_test/single_run.py, tools/statistical_ensemble_test/user_nl_cam_LENS
…xternals
Moved the statistical_ensemble_test files to cesm (created a new tools directory). Also added pyCECT to externals.cfg (I made it *not* required).  I'll do a separate PR for CIME to remove pyCECT from there.
none
https://github.com/ESMCI/cime/issues/4262
No
=> moved statistical ensemble test to cesm.  added pyCECT to externels

manage_externals/README.md, manage_externals/checkout_externals, manage_externals/manic/checkout.py, manage_externals/manic/externals_description.py, manage_externals/manic/externals_status.py, manage_externals/manic/repository_factory.py, manage_externals/manic/repository_git.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py, manage_externals/manic/utils.py, manage_externals/test/test_sys_checkout.py, manage_externals/test/test_sys_repository_git.py, manage_externals/test/test_unit_externals_description.py, manage_externals/test/test_unit_externals_status.py, manage_externals/test/test_unit_repository.py, manage_externals/test/test_unit_repository_git.py, manage_externals/test/test_unit_repository_svn.py, manage_externals/test/test_unit_utils.py
Updates manage_externals to latest tag (manic-v1.2.0)
Contributors other than yourself, if any: @johnpaulalex
johnpaulalex
=> update to manic-v1.2.0

manage_externals/README.md, manage_externals/checkout_externals, manage_externals/manic/checkout.py, manage_externals/manic/externals_description.py, manage_externals/manic/externals_status.py, manage_externals/manic/repository_factory.py, manage_externals/manic/repository_git.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py, manage_externals/manic/utils.py, manage_externals/test/test_sys_checkout.py, manage_externals/test/test_sys_repository_git.py, manage_externals/test/test_unit_externals_description.py, manage_externals/test/test_unit_externals_status.py, manage_externals/test/test_unit_repository.py, manage_externals/test/test_unit_repository_git.py, manage_externals/test/test_unit_repository_svn.py, manage_externals/test/test_unit_utils.py
Reverts ESCOMP/CESM#216  Problems were found here.
=> Revert "update to manic-v1.2.0"

manage_externals/.github/workflows/bumpversion.yml, manage_externals/.github/workflows/tests.yml, manage_externals/README.md, manage_externals/checkout_externals, manage_externals/manic/checkout.py, manage_externals/manic/externals_description.py, manage_externals/manic/externals_status.py, manage_externals/manic/repository_factory.py, manage_externals/manic/repository_git.py, manage_externals/manic/repository_svn.py, manage_externals/manic/sourcetree.py, manage_externals/manic/utils.py, manage_externals/test/README.md, manage_externals/test/test_sys_checkout.py, manage_externals/test/test_sys_repository_git.py, manage_externals/test/test_unit_externals_description.py, manage_externals/test/test_unit_externals_status.py, manage_externals/test/test_unit_repository.py, manage_externals/test/test_unit_repository_git.py, manage_externals/test/test_unit_repository_svn.py, manage_externals/test/test_unit_utils.py
Update to manic-1.2.2 
Fixes: #217 
Testing performed (automated tests and/or manual tests): manage_externals system and unit tests.
=> try again to update manic

cime_config/config_compsets.xml, cime_config/config_pes.xml, cime_config/testlist_allactive.xml
Add BLT1850_v0c compset at ne30pg3_t061 resolution.
Fixes: #222
=> Add BLT1850_v0c compset

tools/statistical_ensemble_test/single_run.py
This PR adds the three new GPU options introduced in https://github.com/ESMCI/cime/pull/4396 to the ensemble consistency test workflow so that they can be used for the test simulations on GPU.
The `ROF_NCPL` XML variable is also updated to work with NUOPC driver for a nine-time-step run.
=> Update new GPU options and ROF_NCPL for ECT workflow

cime_config/config_pes.xml, cime_config/testmods_dirs/allactive/defaultiomi/shell_commands
Update tasks counts for derecho testing for CESM2.2.2
=> Update derecho tasks counts for CESM2.2.2

cime_config/config_pes.xml, cime_config/testmods_dirs/allactive/defaultiomi/shell_commands
Update tasks counts for testing on derecho for CESM2.1.5.
=> Update tasks counts for 2.1.5

tools/statistical_ensemble_test/ensemble.py, tools/statistical_ensemble_test/single_run.py
Allows an ensemble of up to 2000 members.  Also allows you to specify an ensemble start number (this is so you could generate 100 members at a time, for example).
just me
N/A
just a new option added (--es)
testes
=> allow larger ens size and non-zero start

Externals.cfg, cime_config/config_compsets.xml, manage_externals/.github/workflows/bumpversion.yml, manage_externals/checkout_externals, manage_externals/manic/checkout.py, manage_externals/manic/repository_git.py, manage_externals/manic/repository_svn.py, manage_externals/test/repos/README.md, manage_externals/test/test_sys_checkout.py
Update manage externals and add hook to checkout cprnc with cime.
=> update manage externals and cime interface

Externals.cfg, cime_config/config_compsets.xml
=> Adding BSMYLE compset and definitions to config_compsets.xml

cime_config/config_pes.xml
Update some pelayouts for derecho
=> update some pelayouts for derecho

.gitmodules, cime_config/testlist_allactive.xml
Moved testing from POP to MOM.  
The fullactive testlist is still evolving.
=> Update testlist for CESM3. 

.gitmodules
=> cesm3_0_alpha03a 

.lib/git-fleximod/git_fleximod/cli.py, .lib/git-fleximod/git_fleximod/git_fleximod.py, .lib/git-fleximod/git_fleximod/gitinterface.py, .lib/git-fleximod/git_fleximod/submodule.py, .lib/git-fleximod/git_fleximod/utils.py, .lib/git-fleximod/pyproject.toml, .lib/git-fleximod/tbump.toml
Update git-fleximod to v0.9.0
superceeds #275 
Fixes: https://github.com/ESMCI/git-fleximod/issues/61
=> Update/git fleximod0.9.0

.gitmodules, ChangeLog
ctsm answer changing tag
Contributors other than yourself, if any:  CSEG
No
prealpha tests
=> cesm3_0_alpha03b

.gitmodules, ChangeLog
=> cesm3_0_alpha03c candidate

.gitmodules, ChangeLog
Updated externals for cesm3_0_alpha03d
clm answer changing tag.
CSEG
No
=> cesm3_0_alpha03d candidate

.gitmodules, ChangeLog
Update clm tag and remove cice from ChangeLog
=> Update clm tag and remove cice from ChangeLog

.gitmodules, ChangeLog
Updates for cesm3_0_alpha04b testing.
=> Update for cesm3_0_alpha04b testing.

.github/workflows/derecho.yaml
=> try an update

.github/workflows/derecho.yaml
=> another update

.gitmodules, ChangeLog
=> cesm3_0_alpha05b update WW3 tag.

cime_config/config_pes.xml
Improved pelayouts for fully coupled configurations with ww3.
=> update pelayouts for LT and MT fully coupled

.gitmodules, ChangeLog, cime_config/config_pes.xml
Updates fully coupled pe layouts for L and XL settings.   
=> Cesm3.0 alphabranch

.gitmodules, ChangeLog
Updates for cesm3_0_alpha05d testing.
=> Update  for cesm3_0_alpha05d testing

cime_config/config_compsets.xml
=> add missing mosart model to fully active compsets

README.rst
Update link under section 1.3 (Porting CIME)
None
https://github.com/ESCOMP/CESM/issues/240, partially
User interface changes?: [ No ]
None
=> Update README.rst to fix one doc link

.gitmodules, ChangeLog, cime_config/testlist_allactive.xml
Update .gitmodules and ChangeLog for cesm3_0_alpha06a.
Removed f09_t232.BLTHIST tests.
=> Updates for cesm3_0_alpha06a prealpha testing.

.gitmodules, ChangeLog
Update externals and ChangeLog for cesm3_0_alpha06b testing.
=> Update for cesm3_0_alpha06b testing

.gitmodules, ChangeLog
Update .gitmodules and ChangeLog for cesm3_0_alpha06c testing.
=> Update for cesm3_0_alpha06c testing.

.gitmodules, ChangeLog
cesm3_0_alpha06d updates for testing
=> cesm3_0_alpha06d updates for testing

.gitmodules, ChangeLog
Update for cesm3_0_alpha006d testing with fix for cice divide by zero.
=> Update for cesm3_0_alpha06d testing

.gitmodules, ChangeLog
Try again to fix cice divide by zero for cesm3_0_alpha06d
=> Fix cice divide by zero for cesm3_0_alpha06d

.gitmodules, ChangeLog
Update for cesm3_0_alpha06e testing.  I probably wont start testing for a couple of days.
=> Update for cesm3_0_alpha06e testing

.gitmodules, ChangeLog, cime_config/testlist_allactive.xml
Update for cesm3_0_alpha06f testing.
=> Update for cesm3_0_alpha06f testing.

.gitmodules, ChangeLog, cime_config/testlist_allactive.xml
Update for cesm3_0_alpha06g testing.
=> Update for cesm3_0_alpha06g testing.

.gitmodules, ChangeLog
Update for cesm3_0_alpha07b testing
=> Update for cesm3_0_alpha07b testing

.gitmodules, ChangeLog, cime_config/testlist_allactive.xml
Update for cesm3_0_alpha07c testing.
=> Update for cesm3_0_alpha07c testing

.gitmodules, ChangeLog
Update CUPiD extenal to fix testing.
=> Update CUPiD external to fix testing.

.github/workflows/preview_namelist.yaml, .gitmodules, ChangeLog
Update cam, cime, ccs_config tags and ChangeLog for alpha07d testing.
=> Update cam tags for alpha07d testing
